### ISSUE TITLE
Mangademon extension does not display manga name

### ISSUE THREAD

**Issue by SahilDabhi** [TheNetsky/Netskys-Extensions#102]
**Describe the bug**
Whenever we try to open any manga from mangademon it just previews a blank screen and the chapters are provided but the name of the manga does not show.

**To Reproduce**
1. Go to 'mangademon' extension in the 'Discover' tab of the application
2. Click on 'any manga'
3. We get to see blank screen and the chapters will be displayed but the name is not shown

Image and video preview
 provided in the next comment

**App version**
- v0.8.7-r12

**Source WITH source version**
- MangaDemon 1.0.6

**Additional context**

before reloading the extension this happened

![WhatsApp Image 2024-03-16 at 12 33 55 PM](https://github.com/TheNetsky/netskys-extensions/assets/80204672/ba6b9b70-56de-4eed-ba28-49bb3b5f5f96)

(https://github.com/TheNetsky/netskys-extensions/assets/80204672/cc60754a-af2f-4a56-8bb7-35720af4638c)

**Comment by SahilDabhi** [comment]
Probably just change

the domain name to


const MD_DOMAIN = 'https://demontoon.org';

**Comment by SahilDabhi** [comment]
Image and video preview


https://github.com/TheNetsky/netskys-extensions/assets/80204672/b537f65c-4feb-4f24-b1db-b1e7e67354f8

![WhatsApp Image 2024-03-16 at 12 59 05 PM](https://github.com/TheNetsky/netskys-extensions/assets/80204672/77977b1b-0578-4bcc-8d78-8e288cddf577)

**Comment by TheNetsky** [comment]
Works fine for me, likely an issue for you due it being cached.
