### ISSUE TITLE
Mitaku is Broken

### ISSUE THREAD

**Issue by Rednekol** [TheNetsky/Netskys-Extensions#103]
**Describe the bug**
 
Mitaku shows thumbnails in preview , but as soon as you click on any set it shows a white screen. It shows a White Screen while opening any chapter from a set as well

**To Reproduce**
1. Go to the Mitaku Extension on the Discover Tab
2. Click on Any Set (anything new)
3. Click on Ch. 1 - Gallery
4. See Blank White Screen

**Expected behavior**
The set will show no images but Plain White screens on each page.

**Screenshots/Video**
![Screenshot 2024-03-17 at 5 54 58 PM](https://github.com/TheNetsky/netskys-extensions/assets/61759281/3c969ac3-088b-4e13-bd05-a915b89f1b71)
![Screenshot 2024-03-17 at 5 55 18 PM](https://github.com/TheNetsky/netskys-extensions/assets/61759281/1554751b-efc2-4aa8-9884-97d6e7a34305)

**App version**
- v0.8.7-r12

**Source WITH source version**
- Mitaku (1.0.1)

**Additional context**
This only occurs with newer sets, any older sets work as expected

**Comment by TheNetsky** [comment]
fixed
