### ISSUE TITLE
Asurascans not working

### ISSUE THREAD

**Issue by kdmwest** [TheNetsky/Netskys-Extensions#104]
Sinds a week ago my asurascans doesnt show the manwha clicked on the cloud icon and the website is working just fine dont know what to do here are some images

![image](https://github.com/TheNetsky/netskys-extensions/assets/155338635/38b5c3ac-3625-4aef-85d9-c76a39cc7d1a)

![image](https://github.com/TheNetsky/netskys-extensions/assets/155338635/2c3fe6c3-2000-455d-8399-c7447bdce471)

![image](https://github.com/TheNetsky/netskys-extensions/assets/155338635/3244e430-7a3e-4a16-ba5d-6052816a80d7)

**Comment by TheNetsky** [comment]
Wrong repo, also seems to be working fine. Something on your end. Trey reinstalling.
