### ISSUE TITLE
AniList not showing lists on Tracker

### ISSUE THREAD

**Issue by senpaikantuten** [TheNetsky/Netskys-Extensions#111]
AniList does not show manga when adding trackers. This goes for MyAnimeList too.

Reinstalling doesn’t to anything.

![C74F3D50-10FD-4076-8EDC-B276F01EBB7D](https://github.com/user-attachments/assets/36efe67c-d335-43a9-b782-966f6fca944c)

**Comment by senpaikantuten** [comment]
Also adding that it doesn’t update chapters to any previously linked manga anymore.

**Comment by TheNetsky** [comment]
Wrong repo
