### ISSUE TITLE
Omega Scans not rendering images

### ISSUE THREAD

**Issue by Techwiz34** [TheNetsky/Netskys-Extensions#112]
I am trying to read comics from Omega Scans repository, and it will load the page numbers, but it doesn't actually load the images. It does this with every comic i attempt to read.

Here's everything I've tried so far to fix the issue:
- restarted Paperback

- reloaded the repository from settings

-purged and reinstalled the repository

-reinstalled paperback

I am currently running paperback version 0.87r-12 on an iPhone XS, and the iOS version installed is 17.5.1.

**Comment by TheNetsky** [comment]
Wrong repo
