### ISSUE TITLE
Cannot view chapter images from Asurascans any more

### ISSUE THREAD

**Issue by Jedka** [TheNetsky/Netskys-Extensions#118]
**Describe the bug**
Series from Asurascans still appear correctly in my library and new chapters are listed, but attempting to read chapters does not load any images. 

**To Reproduce**
1. Go to a series from Asurascans
2. Click on one of the chapters (read or unread, doesn’t matter)
3. Wait for it to load
4. See a blank page and < 1 of 0 > shown in the bottom right

**Expected behavior**
The chapter images should be shown. 

**Screenshots/Video**

![IMG_2580](https://github.com/user-attachments/assets/5557344d-81d4-4137-b378-b6a94b16880a)
![IMG_2581](https://github.com/user-attachments/assets/b6c146cf-b4b1-4324-8aca-01d25c8c4dce)

**App version**
- v0.8.9-r28

**Source WITH source version**
![IMG_2582](https://github.com/user-attachments/assets/aea4926a-5e7c-4380-a822-e9a8f236dfe5)

**Additional context**
This was working up until a week or two ago, but is now happening for all series from Asurascans. The Discover page still works normally, it’s just an issue when attempting to view chapter images.

**Comment by TheNetsky** [comment]
Wrong repo

**Comment by Ivanmatthew** [comment]
> **Describe the bug** Series from Asurascans still appear correctly in my library and new chapters are listed, but attempting to read chapters does not load any images.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to a series from Asurascans
> 2. Click on one of the chapters (read or unread, doesn’t matter)
> 3. Wait for it to load
> 4. See a blank page and < 1 of 0 > shown in the bottom right
> 
> **Expected behavior** The chapter images should be shown.
> 
> **Screenshots/Video**
> 
> ![IMG_2580](https://private-user-images.githubusercontent.com/29992396/391267601-5557344d-81d4-4137-b378-b6a94b16880a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMwNTAyMDksIm5iZiI6MTczMzA0OTkwOSwicGF0aCI6Ii8yOTk5MjM5Ni8zOTEyNjc2MDEtNTU1NzM0NGQtODFkNC00MTM3LWIzNzgtYjZhOTRiMTY4ODBhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAxVDEwNDUwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4ZjMxNzlhMDNhMTU3N2EyZGJjY2ZhZTdiYWUzZDA0MDI3NjhkNmM3YTI4M2I1ZjFlNzc5YTJiMzI1YzgzNTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.aLTd0egk_esYk7tWPCAp9mMtN_ykbjc730gz3_ydaf0) ![IMG_2581](https://private-user-images.githubusercontent.com/29992396/391267606-b6c146cf-b4b1-4324-8aca-01d25c8c4dce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMwNTAyMDksIm5iZiI6MTczMzA0OTkwOSwicGF0aCI6Ii8yOTk5MjM5Ni8zOTEyNjc2MDYtYjZjMTQ2Y2YtYjRiMS00MzI0LThhY2EtMDFkMjVjOGM0ZGNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAxVDEwNDUwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5MTY4NThkNmRiOGI3YTAyMTExM2U5ZDBiZDZiMTAzODVhOTgxYjdlMTYyODI3YTc3ZDk3YzNiZDQ4ZTZkNWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.73buAcgEWW2i-KS_N1U9jbzWRt-tjbokQcPji5sScu0)
> 
> **App version**
> 
> * v0.8.9-r28
> 
> **Source WITH source version** ![IMG_2582](https://private-user-images.githubusercontent.com/29992396/391267900-aea4926a-5e7c-4380-a822-e9a8f236dfe5.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMwNTAyMDksIm5iZiI6MTczMzA0OTkwOSwicGF0aCI6Ii8yOTk5MjM5Ni8zOTEyNjc5MDAtYWVhNDkyNmEtNWU3Yy00MzgwLWE4MjItZTlhOGYyMzZkZmU1LmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwMVQxMDQ1MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNmM4YTg3MTY2Zjc4ZDRiOGUwNzY2NWRlNjgwN2NmMzgxZmY3ZTAzZTNmNDRiNjc3NDE5NjkzMmRiZDY4Nzk1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.jQf8W4f6n8kJoNkMW6Ty5lU3mcRytwftVwQhw1DkoA8)
> 
> **Additional context** This was working up until a week or two ago, but is now happening for all series from Asurascans. The Discover page still works normally, it’s just an issue when attempting to view chapter images.

I have taken over this source on my repository some time ago. Consider joining Netsky’s basement discord server to stay up-to-date with any changes to sources.
