### ISSUE TITLE
Latest Update for ReadComicOnline

### ISSUE THREAD

**Issue by lodart** [TheNetsky/Netskys-Extensions#20]
Hi ! 
Would it be possible to add the "Latest Update" section for the ReadComicOnline extension ?
Here is the URL : [https://readcomiconline.li/ComicList/LatestUpdate?page=1](https://readcomiconline.li/ComicList/LatestUpdate?page=1)

Thank you :)

**Comment by TheNetsky** [comment]
Will do, forgot about that one!

**Comment by TheNetsky** [comment]
Done, added in 1.0.1
