### ISSUE TITLE
Fix ReadComicOnlineLi

### ISSUE THREAD

**Issue by TheNetsky** [TheNetsky/Netskys-Extensions#22]
- [x] Set cookie for browse listing to "list-view=list" to fix the view more within the app
- [x] Fix User Agent not setting for Cloudflare bypass (App issue)
- [x] Searching broken
- [x] Fix homescreen
- [ ] Comic pages

**Comment by xOnlyFadi** [comment]
Hey NetSky I fixed ReadComicOnlineLi cloudflare problem and it's working with no problems and two things are broken search when searching normal titles and viewmore homepage ![image](https://user-images.githubusercontent.com/63213308/161664280-3d26a9c2-f95c-468c-ac85-206b84d8b9c8.png)

**Comment by xOnlyFadi** [comment]
the thing is in readcomiconline.li cloudflare protection is if the user-agent is different you can't scrape the site but if it's the same user-agent for bypassing and reuqests it will work with no problems at all

**Comment by TheNetsky** [comment]
Reference See #23

**Comment by TheNetsky** [comment]
Source has been discontinued.
