### ISSUE TITLE
Mangahere seems to not work

### ISSUE THREAD

**Issue by senorYME** [TheNetsky/Netskys-Extensions#24]
checked their site still works just seems paperback isn't loading images

**Comment by TheNetsky** [comment]
Fixed in 2.0.5

**Comment by senorYME** [comment]
thanks bro

**Comment by senorYME** [comment]
also to note some manga chapters just disappear for example ![image](https://user-images.githubusercontent.com/98798167/164286842-8c399daa-d668-4aa6-9487-13db77818a5e.png)

**Comment by TheNetsky** [comment]
I know what's causing thatz haven't had time to fix

**Comment by senorYME** [comment]
alright and thanks bro

**Comment by TheNetsky** [comment]
Fixed
