### ISSUE TITLE
Mangahere - source showing licensed for latest chapters

### ISSUE THREAD

**Issue by XenitXTD** [TheNetsky/Netskys-Extensions#25]
Lately when using mange here source when it gets to latest chapters it starts to load then switches to single image below

Chapters work fine on website so not sure where the issue is here

![image](https://user-images.githubusercontent.com/5268461/168011443-39f8d496-75a4-45fc-99dc-885061bf7156.png)

**Comment by TheNetsky** [comment]
Kind of literally missing all the useful information here;
- Manga
- Chapter
- Source
- Source version
- App version

Can't do anything with just this info,

**Comment by XenitXTD** [comment]
@TheNetsky appologies

I know for a fact it's an issue on

- Tales of demons and gods
- Apotheosis 912-915 916 works again
- One Piece 1049 tested

The fact that the result is mixed of working and not working leaves me wondering

Further testing on this shows that the chapter reference is there but no pages so maybe it's a case of better messaging that the chapter reference is there but no pages to load rather than licensed?

![image](https://user-images.githubusercontent.com/5268461/168102081-07508ed6-9f66-41c6-bd98-ffbeb78eaec2.png)

Missing chapter apotheosis 913

![image](https://user-images.githubusercontent.com/5268461/168104285-1c74806c-95ab-4b27-9629-edb2f735f066.jpeg)

One piece app shows more chapters than website?

![image](https://user-images.githubusercontent.com/5268461/168104429-be3aca4d-d3fa-4a47-a6bc-9e46b2bab816.jpeg)

![image](https://user-images.githubusercontent.com/5268461/168104453-5345a131-1d2d-4fcc-8feb-d30b1f1065b3.png)

**Comment by TheNetsky** [comment]
Uhhh?

**Comment by mkaito** [comment]
From what I can tell, this seems to have been a transient issue at the source itself.
