### ISSUE TITLE
[Notice] Doki1001, MangaHatachi & MangaGohan seem to have been DMCA'ed

### ISSUE THREAD

**Issue by Manukineko** [TheNetsky/Netskys-Extensions#26]
The title says it all.
https://twitter.com/Aims_Japan/status/1517427709928165376
Doki1001 & MangaHatachi return a no server found error (with or without a VPN)
Using the isitdownrightnow.com service return that the two website are down.

**Comment by TheNetsky** [comment]
Thanks for the info, will remove the sources
