### ISSUE TITLE
Manga stopped opening on readm 

### ISSUE THREAD

**Issue by Sahibs1** [TheNetsky/Netskys-Extensions#27]
On readm manhwas that I have favorited are not opening when I click them. The chapters do not show up and I cannot read anything. It is only for select manhwas too. 
![4688425E-3191-48C7-885D-536806FC1D30](https://user-images.githubusercontent.com/108420410/177006600-bc369e18-6363-4af6-99fd-33c0d9a3b6f3.png)

**Comment by TheNetsky** [comment]
Only seems to be an issues for some specific manga, I'll take a look at it later.

**Comment by TheNetsky** [comment]
Fixed
