### ISSUE TITLE
MangaBox: MangaNato is broken

### ISSUE THREAD

**Issue by shaunKodi** [TheNetsky/Netskys-Extensions#32]
**Describe the bug**
Doesn't pull any manga from manganato website

**To Reproduce**
1. Go to source and browse on manganato

**Expected behavior**
Manga is expected to be shown. Latest, popular etc etc.

**App version**
- v0.4-r69

**Source WITH source version**
- Readm 1.0.1

**Additional context**
I have a feeling that I'm in the wrong repo for the issues, putting this here since after hours of searching,I still couldn't find the repo with mangabox sources.

Someone please point me to the correct place if this is the wrong one to open this issue

Photo:
![image](https://user-images.githubusercontent.com/53500203/180652716-5a606faa-d111-4fe3-8ea9-ae43b951b2bb.jpeg)

**Comment by TheNetsky** [comment]
This is indeed the wrong repo.
Also no video is shown so got no idea what you mean.

Seems like an issue on your end.

**Comment by shaunKodi** [comment]
Updated with a photo, this is what I see when I try to browse in MangaNato

**Comment by shaunKodi** [comment]
Any idea of the correct repo to post this in?

**Comment by TheNetsky** [comment]
Yep, people had that before, issue on your end.

**Comment by TheNetsky** [comment]
See https://discord.com/channels/965890377896845352/966273746136629258/996571888769847610

**Comment by shaunKodi** [comment]
Don't have access to that channel.....
