### ISSUE TITLE
Manganato broken

### ISSUE THREAD

**Issue by ahuynh30** [TheNetsky/Netskys-Extensions#34]
**Describe the bug**
Issue with all manganato not loading, started happening 2 days ago 

**To Reproduce**
1. Go to mangabox(netsky fork)
2. Install manganato
3. Go to manganato
4. See blank page

**Expected behavior**
should see manga there

**Screenshots/Video**
![DA53ED63-CC30-488C-BFE3-0F5480F272E8](https://user-images.githubusercontent.com/78059807/181573570-933d98dc-df43-4b52-93d2-2c97f0ae1af5.jpeg)
![E5088D15-FA71-4AC1-B925-B4C1338649E3](https://user-images.githubusercontent.com/78059807/181573577-090813a5-6504-41f8-821e-330f1c7ce022.png)
![7B32C59A-97C0-43B5-8C34-61C952373C9B](https://user-images.githubusercontent.com/78059807/181573584-5f3c03c9-e68f-4f9c-8266-65717e2b2c2f.png)

![Uploading C5196408-3436-44E2-8DD0-F09EEE4FC56E.png…]()

**App version**
- v0.7-r46

**Source WITH source version**
- Readm 1.0.1

**Additional context**

**Comment by ahuynh30** [comment]
Wait I just tried one more thing where I deleted the app and restored a backup I created, it seems fine sorry for the trouble! I only noticed because I went on my other device and manganato was working fine.

**Comment by shaunKodi** [comment]
Does anyone know why this happens? It happened to me twice so far and the only way I found to recover from is uninstalling and reinstalling along with a backup.

**Comment by TheNetsky** [comment]
Afaik only solution thus far
