### ISSUE TITLE
Cannot open manga from Mangahub

### ISSUE THREAD

**Issue by kayzerrex** [TheNetsky/Netskys-Extensions#35]
Describe the bug

Everytime I tried to open a manga from mangahub it shows an error message (attached)

To reproduce

Install Mangahub
Go to Mangahub
Open any manga

Expected Behavior

Manga picture should load

Screenshot

![F18E54B8-F8F4-46F1-AD31-1FFE4B63AF7E](https://user-images.githubusercontent.com/110217538/181687343-5e3fdaae-e884-4699-b8c6-7ff2d7ab94c6.png)

**Comment by chlm1556** [comment]
I have the same problem +1
Here some additional photos..
![4CDC75AF-7CFE-4DE3-BFB3-D551E0A2078D](https://user-images.githubusercontent.com/25506062/181692626-4904f824-7c61-4b6d-bbf5-24c0625ace78.png)
![35B4A0EC-D116-4AD6-9553-38CF107EC10B](https://user-images.githubusercontent.com/25506062/181692631-6e680d3e-0c52-4ceb-a248-cfe5ef7df69d.png)
![62CB471E-9E6B-44AB-9AED-B78B41EC8E0F](https://user-images.githubusercontent.com/25506062/181692632-e8b42d15-07e9-4c04-b51c-675d28c72f44.png)

**Comment by senorYME** [comment]
for me manhahub is installed but all bookmarked manga when open are just blacked out; but they work on original site ; I have a feeling the site updated something and extension for now is borked

**Comment by TheNetsky** [comment]
Fixed 2.0.5, do the Cloudflare bypass.
