### ISSUE TITLE
Paperback just blank after installing

### ISSUE THREAD

**Issue by senpaikantuten** [TheNetsky/Netskys-Extensions#36]
Tried re-installing the app and this happened. Just a black screen. Help?

![AF3BC00A-2B83-411D-8B63-CCEB65A13A3C](https://user-images.githubusercontent.com/107646075/181925963-8284e9d9-5dd5-448b-b7ef-130780ae89f2.png)

**Comment by TheNetsky** [comment]
Not a source issue.
