### ISSUE TITLE
Mangahub stopped working

### ISSUE THREAD

**Issue by yduncoo** [TheNetsky/Netskys-Extensions#37]
Mangahub not working. I've tried reinstalling the source too per step # 15 in the faq on discord, but it still throws the same error.

This is what shows up when opening paperback:
![68565FEA-7148-4BF0-A71F-0CE2EBC69804](https://user-images.githubusercontent.com/36029647/181937730-6c956469-ab8e-4195-8e43-951ceae8c109.png)

If I try to do Cloudflare it opens this:
![E47684B4-26B1-478C-9A03-32139118BA2F](https://user-images.githubusercontent.com/36029647/181937753-e29661eb-be22-40be-8978-fa68c21eaef2.png)

These are my logs:
https://pastebin.com/6QFCaNX6

**Comment by TheNetsky** [comment]
Known.

**Comment by TheNetsky** [comment]
Fixed in 2.0.6
