### ISSUE TITLE
Repo Links not working

### ISSUE THREAD

**Issue by senpaikantuten** [TheNetsky/Netskys-Extensions#38]
Every time I click “Click Here” to get a repo link it’s just stuck in this white loading space without actually getting into the link. This happens to every link.
![3F580A04-D604-4D8D-BA3F-07675B4E92AA](https://user-images.githubusercontent.com/107646075/182008321-1cd8903d-7cba-411d-93c3-dc351442004e.png)

**Comment by xOnlyFadi** [comment]
add it manually to the app

**Comment by TheNetsky** [comment]
Issue on your end. Try VPN or different network.
