### ISSUE TITLE
MangaHub | Source broken

### ISSUE THREAD

**Issue by TheNetsky** [TheNetsky/Netskys-Extensions#40]
MangaHub now requires a token for it's API which needs to be intercepted.
However they've recently added a request limit, when surpassing this limit you'll get temp banned.

See https://github.com/tachiyomiorg/tachiyomi-extensions/pull/12978

Source will not be fixed until either MangaHub reverts this issue or confirmed that website will stop intentionally breaking sources.

**Comment by TheNetsky** [comment]
Dupe of #37

**Comment by PhoenixGre** [comment]
Is this going to be solved soon?

**Comment by TheNetsky** [comment]
> Is this going to be solved soon?

No, source will likely be removed instead.
