### ISSUE TITLE
Manga Katana source broken

### ISSUE THREAD

**Issue by travgarv** [TheNetsky/Netskys-Extensions#41]
**Describe the bug**
When attempting to read a manga using mangakatana it will only show the last page of the chapter, making the manga unreadable in app.

**To Reproduce**
1. view any manga in mangakatana

**Expected behavior**
Being able to read the manga

**Screenshots/Video**

**App version**
- v0.7-r46

**Source WITH source version**
- Mangakatana 2.0.1

**Additional context**

**Comment by TheNetsky** [comment]
Fixed in 2.0.2
