### ISSUE TITLE
Duplicate title ids detected keeps showing up when I read anything

### ISSUE THREAD

**Issue by Sahibs1** [TheNetsky/Netskys-Extensions#43]
I keep getting a Paperback: Duplicate title ids
detected, please run database repair. Error message. I don’t know how to fix this. Black clover chapter 334 spoiler btw
![DD9F8259-7A34-4DD4-BCC3-3894B64FFE57](https://user-images.githubusercontent.com/108420410/185665515-94fb0e1c-1e41-481d-b5eb-f1b074fa425e.png)

**Comment by TheNetsky** [comment]
Run database repair, also this is an app issue. Not a source issue.
