### ISSUE TITLE
Image not showing in "Popular Comics" section for ComicOnlineFree source

### ISSUE THREAD

**Issue by chailjc** [TheNetsky/Netskys-Extensions#44]
**Describe the bug**
"The image is unavailable" message appears in the comic covers under the Popular Comics section.

**To Reproduce**
1. Go to 'ComicOnlineFree'
2. Scroll to "Popular Comics"
3. See error

**Expected behavior**
Comic image appears.

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/89789474/186128390-2bef32f1-95b5-46c8-b772-d3668fa527f0.png)

**App version**
- v0.7-r47

**Source WITH source version**
- ComicOnlineFree 1.0.0

**Comment by TheNetsky** [comment]
Only that section?

**Comment by chailjc** [comment]
Only that section, images show up in other parts of the app

**Comment by TheNetsky** [comment]
Fixed 1.0.1
