### ISSUE TITLE
Manganato | Fix image server switch

### ISSUE THREAD

**Issue by StrangePeanut** [TheNetsky/Netskys-Extensions#46]
## Describe the bug

When switching **image server** to **server 2** the app continues to try **server 1** instead. I am able to read just fine by switching to server 2 using a web browser.

## To reproduce

Steps to reproduce the behaviour:

1. Use a managed network that blocks **server 1 (mkklcdnv6tempv5.com)**
2. Go to Manganato image server settings
3. Set server to **server 2**
4. Try reading one of the titles below
5. Images cannot be loaded

### Some affected titles

- Star Martial God Technique
- Rebirth Of The Urban Immortal Cultivator
- Boku No Hero Academia

## Expected behaviour

When image server is set to **server 2** the app should actually use **server 2**

## Screenshots/Video

![manganato20220826](https://user-images.githubusercontent.com/56807288/186839898-6abede8f-e6f7-43d7-94e0-fce40f3db3b8.jpeg)

## App version

- v0.7-r47

## Source

- Manganato 3.0.6

## Additional context

Thinking the issue was related to https://github.com/TheNetsky/netskys-extensions/issues/34 I have reinstalled the app and reimported backup to no avail

**Comment by senorYME** [comment]
yep same issue just started today

**Comment by SenorWhyMe** [comment]
trust me ; back up paperback delete app and reinstall and add back the backup it works again

**Comment by StrangePeanut** [comment]
@SenorWhyMe that issue is unrelated to this issue. This issue is replicable on reinstall, ie it keeps trying image server 1 despite being set to server 2.

@TheNetsky afraid this hasn't been solved. Now it says 'Failed to load image. The operation couldn't be completed. Invalid argument'

**Comment by StrangePeanut** [comment]
@TheNetsky Tried again just now. It finally seems to work. Thanks for your work :)
