### ISSUE TITLE
MangaDex Source not working

### ISSUE THREAD

**Issue by nyck301** [TheNetsky/Netskys-Extensions#47]
**Describe the bug**
For some odd reason even though I have been reading all day on paperback using the MangaDex source from the "Browse Extensions Primary (Netsky Fork) it is now not working for me.

**To Reproduce**
1. I can not search any manga on the MangaDex source 
2. If I try to click on a saved series in my library from MangaDex i get an error 

**Expected behavior**
I should be able to pull up manga from the MangaDex source just fine with no issue like I have been today.

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/113084637/189039556-9605585f-705e-4dc3-8d46-ce6cf62e8d12.png)

![image](https://user-images.githubusercontent.com/113084637/189039572-779f9030-794b-4f44-91de-c2647cd47ea3.png)

**App version**
- v0.7-r46

**Source WITH source version**
- The Source is MangaDex nar1n 2.1.9

**Additional context**

**Comment by TheNetsky** [comment]
First go to respective website before asking here, thanks. That will save us both some time.
