### ISSUE TITLE
Mangakatana Source Broken - Only Load First Page

### ISSUE THREAD

**Issue by vincenciusgeraldo** [TheNetsky/Netskys-Extensions#48]
**Describe the bug**
Mangakatana only load the first page when reading a chapter, making Mangakatana unusable.

**To Reproduce**
1. Read any chapter in Mangakatana

**Expected behavior**
All pages should be loaded and readable

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/17944555/190840115-3582159f-d536-4aff-9e48-cdb20b280e73.png)

**App version**
- v0.7-r69

**Source WITH source version**
- MangaKatana 2.0.3

**Additional context**
Used on IOS 16.1

**Comment by TheNetsky** [comment]
Fixed 2.0.4
