### ISSUE TITLE
McReader Broken?

### ISSUE THREAD

**Issue by Error404-NameNotFound** [TheNetsky/Netskys-Extensions#52]
**Describe the bug**
Can’t access mcreader source to read manga due to cloudfare.

**To Reproduce**
1. Go to McReader tab/source.
2. Click on the cloud icon in the upper right corner.
3. Go back to McReader tab/source and get an error.

**Expected behavior**
Well, I expected that I would enter the website and then refresh the source page to continue reading manga.

**Screenshots/Video**
![CB665F6C-45DE-4DDD-A3D2-2CE846878432](https://user-images.githubusercontent.com/23133571/194134894-ac3eb9ce-5b63-4246-a6e6-2a3bf5d9214d.jpeg)
![11899487-582A-407E-904B-9721DFA47386](https://user-images.githubusercontent.com/23133571/194134899-3cfb3ff2-10d1-44f4-858a-e85e311ec69b.jpeg)

**App version**
- v0.7-r46

**Source WITH source version**
- McReader 1.0.2

**Additional context**
I’m not sure if it’s a source problem or just me.

**Comment by TheNetsky** [comment]
Issue will not be fixed, cloudflare related. Wait for the site to lower the protections.
