### ISSUE TITLE
Bato.to doesn't show Thumbnails

### ISSUE THREAD

**Issue by serideri** [TheNetsky/Netskys-Extensions#54]
**Describe the bug**
When opening the App and going into the Library, Bato.To doesn't show any thumbnails. This issue only happens with Bato.To and migrating it into the same source only fixed it for a short while, before it starts happening again. (Reloading the Mangas doesn't work either)

**To Reproduce**
1. Go to 'Library'
2. Click on 'All Manga'
3. Scroll down to 'Mangas with Bato.To as source'
4. See no thumbnails (Or only Paperback logo)

**Expected behavior**
It is expected to show the thumbnails of the mangas when opening the library.

**Screenshots/Video**

**App version**
- v0.7-r46

**Source WITH source version**
- Bato.To 2.0.3

**Additional context**

**Comment by TheNetsky** [comment]
Not a source of mine nor that I maintain, open an issue on the correct repo.
