### ISSUE TITLE
McReader/MangaKatana issues

### ISSUE THREAD

**Issue by PhoenixGre** [TheNetsky/Netskys-Extensions#55]
Most McReader manhwas with more than 100 chapters start at a way higher chapter, ive checked the site itself, and they start at chapter 1 there. Also is there an eta for MangaKatana's thumbnail fix?

**Comment by TheNetsky** [comment]
- MangaKatana issue won't be fixed
- Other issue I'll take a look at later

**Comment by TheNetsky** [comment]
McReader has been fixed
