### ISSUE TITLE
Mangakatana shows 1 page only

### ISSUE THREAD

**Issue by travgarv** [TheNetsky/Netskys-Extensions#57]
**Describe the bug**
Any manga using the mangakatana source only shows me the first page

**To Reproduce**
1. go to mangakatana source
2. Click on any manga
3.  See only one page

**Expected behavior**
Display full chapter.

**Screenshots/Video**

![53654432-9026-46A3-A5B5-47C1D210F2DD](https://user-images.githubusercontent.com/111518113/198751983-9ea0f672-5405-4691-bcff-a8e4de704a32.png)

**App version**
- v0.7-r46

**Source WITH source version**
- Mangakatana -netsky 1.0.6

**Additional context**
n/a

**Comment by TheNetsky** [comment]
Very old source version, update your sources.
