### ISSUE TITLE
[Tsumino] Many titles crashing upon opening

### ISSUE THREAD

**Issue by Chromagram** [TheNetsky/Netskys-Extensions#58]
**Describe the bug**
It doesn't happen to all titles, but many titles you click to read on the new Tsumino source crashes Paperback as soon as you open them.

**To Reproduce**
1. Open any random title under the Tsumino source.
2. Attempt to open a chapter. Sometimes, it is worth trying multiple chapters as one may work fine while another crashes Paperback.

**Expected behavior**
Titles should load the appropriate manga when selected instead of crashing. Just to make sure, I loaded the corresponding manga from the Tsumino site directly, and it has no errors from the site itself.

**Screenshots/Video**
N/A, just crashes the whole app with no popups.

**App version**
- v0.7-r46

**Source WITH source version**
- Tsumino 1.0.2

**Additional context**
If it helps, I have about 5 other sources I use that have no major full-crash level issues, just as a control sample.

**Comment by TheNetsky** [comment]
Not a source of mine, open the bug report on the correct repo.
