### ISSUE TITLE
Mangakatana not working

### ISSUE THREAD

**Issue by AshnakAGQ** [TheNetsky/Netskys-Extensions#60]
I can see the catalogue but the pages aren’t loading. Getting errors in the app (decoding error, data corrupted, not valid json, invalid server certificate)

**Comment by Nonerex** [comment]
Same issue with flamescan. Pages are not loading.

**Comment by TheNetsky** [comment]
> Same issue with flamescan. Pages are not loading.

Not from this repo.



> I can see the catalogue but the pages aren’t loading. Getting errors in the app (decoding error, data corrupted, not valid json, invalid server certificate)

Issue on your end/network. Use a VPN.

**Comment by Nonerex** [comment]
It’s from the nmns extensions so it is

**Comment by TheNetsky** [comment]
> It’s from the nmns extensions so it is

Correct and this is my repo, Netsky's repo, not NMN's.
