### ISSUE TITLE
Cloudflare authentication not working with mangapill

### ISSUE THREAD

**Issue by soulix12** [TheNetsky/Netskys-Extensions#63]
**Describe the bug**
Stuck at validating if your a bot when trying the cloudflare specifically to the source mangapill
![image](https://user-images.githubusercontent.com/44424505/228391201-b9603962-ded0-4751-80a2-af3beedd939a.png)

**To Reproduce**
1. Go to mangapill
2. Click on cloudflare
3. Validate your not a bot
4. Stuck at the validation

**Expected behavior**
Cloudflare should have validated

**Screenshots/Video**
Screenshot provided above

**App version**
- 16.1.1

**Source WITH source version**
- gamefuzzy 2.1.2

**Comment by TheNetsky** [comment]
Not a source from me or this repo, place issues on their corresponding repos.
