### ISSUE TITLE
Readm - Manga locked behind login

### ISSUE THREAD

**Issue by vregat** [TheNetsky/Netskys-Extensions#68]
**Describe the bug**
Readm started locking mangas behind login and it is not possible to read them (chapters do not load).

**To Reproduce**
1. Go to ['The Gamer'](https://readm.org/manga/the-gamer-0015)
2. See the message 'You need to LOG IN in order to read this manga.'

**App version**
- v0.8-r56

**Source WITH source version**
- Readm 1.0.1

**Additional context**
Is it possible to add login to extension settings?

**Comment by TheNetsky** [comment]
Just login using the Cloudflare bypass, might add this feature later, not sure.

**Comment by vregat** [comment]
I tried to login via cloudflare bypass but it works only for some mangas, not all of them.

> Just login using the Cloudflare bypass, might add this feature later, not sure.
