### ISSUE TITLE
Manga buddy not working

### ISSUE THREAD

**Issue by Sahibs1** [TheNetsky/Netskys-Extensions#69]
Mangabuddy 1.1.4 is not showing manga when I click on them. I can click on manga but when I click on chapters it is just black. I can scroll and everything but there is nothing there. 
![IMG_0295](https://github.com/TheNetsky/netskys-extensions/assets/108420410/2c871a37-198a-4763-a88d-4cbe44e40e20)

**Comment by Ivanmatthew** [comment]
Use the official format or append the left out details required in the template
