### ISSUE TITLE
Cosplay not showing anything

### ISSUE THREAD

**Issue by im-beggin** [TheNetsky/Netskys-Extensions#70]
**Describe the bug**
HCosplay extension would show nothing upon browsing in.

**To Reproduce**
1. Go to 'HCosplay tab(assuming you have the extension installed)'
2. Click on 'Any category'
4. See nothing would show up but a black screen

**Expected behavior**

**Screenshots/Video**

**App version**
- v0.8.1-r3

**Source WITH source version**
- HentaiCosplay 1.0.3

**Additional context**
clicking on web-page of the extension seems fine and do not require cloudflare verification or anything.
![image_2023-07-08_191603603](https://github.com/TheNetsky/netskys-extensions/assets/92623161/256c526d-00d9-4d43-929d-522b341f56a6)

**Comment by TheNetsky** [comment]
Works fine for me.
