### ISSUE TITLE
IP banned after refreshing library Mangadex 0.8 source

### ISSUE THREAD

**Issue by Mirozuki** [TheNetsky/Netskys-Extensions#72]
**Describe the bug**
I have a large library on dex (about 600 mangas) and I am getting ip banned after refreshing the whole library 

**App version**
- v0.8.2-r1

**Source WITH source version**
- MangaDex (3.0.2)

**Comment by TheNetsky** [comment]
Well, that's because you're making too many requests with all those items. Avoid refreshing them all and refresh collections only.
