### ISSUE TITLE
Unable to use MangaDex 3.0.2

### ISSUE THREAD

**Issue by Mzyene** [TheNetsky/Netskys-Extensions#73]
**Describe the bug**
After enabling MangaDex from the Paperback Community Extensions 0.8 repository, I am unable to see anything pull from the discover and search tabs. Additionally, when attempting to login to my account it continually fails to recognize my credentials even though I've verified the credentials are correct from the base MangaDex website. I've attempted removing and reinstalling the repository and extensions multiple times without success.

**Expected behavior**
To be able to view and search from the Mangadex library

**Screenshots/Video**
![2EFB62FF-DF19-43E2-AAF7-5CDC6610B192](https://github.com/TheNetsky/netskys-extensions/assets/5446149/9514e4a5-7079-477c-9aa2-d0a640ebfc84)

**App version**
- v0.8.3-r2

**Source WITH source version**
- MangaDex 3.0.2

**Comment by TheNetsky** [comment]
Works fine for me, seems to be something on your end. See if you can access the site normally, else try with a VPN.
