### ISSUE TITLE
Webtoon.XYZ

### ISSUE THREAD

**Issue by GiveMeFingers** [TheNetsky/Netskys-Extensions#75]
**Describe the bug**
No option to Cloudflare bypass

**To Reproduce**

**Expected behavior**
There is an option to Cloudflare bypass

**Screenshots/Video**

**App version**
- v0.8.3-r2

**Source WITH source version**
- WebtoonXYZ 3.0.5

**Additional context**
Before the paperback update there was an option to Cloudflare bypass.

**Comment by TheNetsky** [comment]
1. Wrong Repo
2. Cloudflare bypass is on homescreen
