### ISSUE TITLE
Source New Chapter Notificationand 

### ISSUE THREAD

**Issue by tyramsihu** [TheNetsky/Netskys-Extensions#76]
Hi there! Ho to update

**Comment by TheNetsky** [comment]
bruh wat

**Comment by tyramsihu** [comment]
Sorry typo! I mean, How to do automatic update on chapter I’ve bookmarked and turn on the notification when there’s a new chapter? is the feature not avail on ver 0.8 beta yet?

**Comment by TheNetsky** [comment]
Not a feature in 0.8

**Comment by tyramsihu** [comment]
Ah I see, will it get an upgrade and be featured in 0.8 in the future?

**Comment by TheNetsky** [comment]
Eventually.
