### ISSUE TITLE
Mangakakalot not loading after upgrade to v8 and v8 source

### ISSUE THREAD

**Issue by Johnnygitit** [TheNetsky/Netskys-Extensions#77]
**Describe the bug**
Unable to load, totally blank. 

**Screenshots/Video**
![photo_2023-07-25_00-12-45](https://github.com/TheNetsky/netskys-extensions/assets/140428910/a9987579-5216-4c24-bffe-61ef418eefdf)
![photo_2023-07-25_00-12-56](https://github.com/TheNetsky/netskys-extensions/assets/140428910/7d44dad5-5cef-418a-938a-6a6f941ce050)

**App version**
- v0.8.3-r2

**Source WITH source version**
- Mangakakalot Batmeow|4.0.3

**Comment by Johnnygitit** [comment]
![Uploading IMG_4834.png…]()

**Comment by Johnnygitit** [comment]
![IMG_4834](https://github.com/TheNetsky/netskys-extensions/assets/140428910/087a4ddf-3f64-43a7-b179-d24ec524d487)
![IMG_4833](https://github.com/TheNetsky/netskys-extensions/assets/140428910/e2c0e522-8eb7-4c03-8818-cf01facdf940)

**Comment by TheNetsky** [comment]
Reinstall app

**Comment by Johnnygitit** [comment]
It works. Thanks!
