### ISSUE TITLE
Photo save iPadOS 

### ISSUE THREAD

**Issue by CozyChasm** [TheNetsky/Netskys-Extensions#78]
When you save a panel on IPadOS it kicks you out the app. 
**To Reproduce**
1. Go to any series 
2. Hold down on the page 
3. Press share image then save image

**Expected behavior**
Saves the image and that’s it 

**App version**
- v0.8.6

**Source WITH source version**
- Tried all sources I have 

https://github.com/TheNetsky/netskys-extensions/assets/141690380/7ee2251c-2e3c-4cc6-a339-63097c42b984

**Comment by TheNetsky** [comment]
Not a source issue, app issues.
