### ISSUE TITLE
Asurascan not loading

### ISSUE THREAD

**Issue by Dlia65** [TheNetsky/Netskys-Extensions#79]
**Describe the bug**
Asurascan not loading with error messsage. Tried deleting and adding repository again but not luck. Not sure what to do

**To Reproduce**

**Expected behavior**

**Screenshots/Video**
![image](https://github.com/TheNetsky/netskys-extensions/assets/142184038/9521b81f-7009-479f-8813-9764603c49b7)
**App version**
- v.8.6-r2

**Source WITH source version**
- mangastream generic .8  asurascan 3.0.3

**Additional context**

**Comment by TheNetsky** [comment]
Seems like something on your end, unable to replicate this.
