### ISSUE TITLE
Asurascans not loading

### ISSUE THREAD

**Issue by Mihran77** [TheNetsky/Netskys-Extensions#80]
**Describe the bug**
An error pops up whether I open something from Asurascans and the chapters don’t load either

**To Reproduce**
1. Go to Asurascans in the homepage or any of its manga from your library
2. Click on them
3. See error

**Expected behavior**
I expect the chapters to load

**Screenshots/Video**
The error message 

Paperback: JSError Error
[PaperbackError (300)] JSError Error:
CLOUDFLARE BYPASS ERROR:
Please go to the homepage of <https:// asura.nacm.xyz> and press the cloud icon. - checkResponseError@
@:1988:32

**App version**
- v0.8.6-r2

**Source WITH source version**
- Asurascans 3.0.3

**Additional context**
Some of the thumbnails are loading and it shows the list of chapters, but doesn’t show any new chapters and if you click any of them the error shows up and the chapter doesn’t load

**Comment by TheNetsky** [comment]
Does load, only 1st image doesn't.

**Comment by Mihran77** [comment]
None of the pages load

**Comment by MtMystery** [comment]
I am still facing this issue but am not getting the error message

**Comment by TheNetsky** [comment]
Source works fine for me, except the first page not loading. Try reinstalling, I personally also have no Cloudflare errors.

**Comment by MtMystery** [comment]
Reinstalling fixed the issue for me. Thanks
