### ISSUE TITLE
AsuraScans Art Cover for Comic does not load after clearing image cache

### ISSUE THREAD

**Issue by MeowTheSnake** [TheNetsky/Netskys-Extensions#82]
**Describe the bug**
After clearing image cache, all cover art for AsuraScans no longer show up and stay as blank / black boxes for comic art. Unable to get cover art to reload after removing source & repo and re-installing.

**To Reproduce**
1. Favorite a comic / manga / etc from AsuraScans
2. Confirm comic art shows up in Library
3. Go to 'Settings'
4. Scroll down to Storage
5. Click on 'Clear Image Cache'
6. Go back to Library to and verify comic art shows up before loading in chapters
7. See blank cover art

**Expected behavior**
Reload cover art from source if a cached image is unavailable

**Screenshots/Video**
![IMG_1788](https://github.com/TheNetsky/netskys-extensions/assets/142695325/83607aba-d9f0-438f-b385-cbc59f9c34f6)

**App version**
- v0.8.6-r2

**Source WITH source version**
- AsuraScans - Netsky | 3.0.3

**Additional context**
N/A

**Comment by TheNetsky** [comment]
Migrate > Asura to Asura

**Comment by MeowTheSnake** [comment]
@TheNetsky Sorry i do not understand what this means. I do not see any way to migrate and the repo source does not offer a "update" to AsuraScan. Can you please provide some additional details / context?

**Comment by MeowTheSnake** [comment]
Hi @TheNetsky i believe i figured out how to perform the Migrate function. I noticed there are 2 options (both of which I've attempted. 'Replace' & 'Merge'). The issue still persists were the cover art will still not show up. Any additional suggestions?
 
![IMG_1789](https://github.com/TheNetsky/netskys-extensions/assets/142695325/1889f8bb-2ddc-4ee2-b49d-a4f79a9f4775)

**Comment by snwyFC** [comment]
Long press affected titles, tap the "Refresh Metadata" button

**Comment by MeowTheSnake** [comment]
@snwyFC , perfect that works. Sucks i need to do each one manually, but hey, the issue is fixed. Thanks again!
