### ISSUE TITLE
MangaDemon mangas don't download and crash on open

### ISSUE THREAD

**Issue by hyoretsu** [TheNetsky/Netskys-Extensions#84]
**Describe the bug**
Title

**To Reproduce**
Get a MangaDemon manga, like Return of the Frozen Player, and try to download/read it

**Expected behavior**
It shouldn't crash

**App version**
v0.8.6-r2

**Source WITH source version**
MangaDemon v1.0.2

**Comment by TheNetsky** [comment]
Fixed
