### ISSUE TITLE
[BUG] ComicOnlineFree manga not loading

### ISSUE THREAD

**Issue by chailjc** [TheNetsky/Netskys-Extensions#87]
**Describe the bug**
ComicOnlineFree manga not loading

**To Reproduce**
1. Go to 'ComicOnlineFree'
2. Click on any comic. Image below will show up
3. See error

**Expected behavior**
For comic and related chapters to appear.

**Screenshots/Video**
![IMG_601F88F24A0B-1](https://github.com/TheNetsky/extensions-generic-0.8/assets/89789474/de704914-2d61-48e4-803f-061a23346e63)

**App version**
- v0.8.7 (3) & v0.8.7 (9)

**Source WITH source version**
- ComicOnlineFree 1.1.5

**Additional context**
Same on both iPhone & iPad. Problem persists despite restarting app, database repair and reinstalling source.

**Comment by Ivanmatthew** [comment]
Can you show us your logs?

**Comment by chailjc** [comment]
Please see attached log
[12-10.Paperback.txt](https://github.com/TheNetsky/netskys-extensions/files/12882552/12-10.Paperback.txt)

**Comment by TheNetsky** [comment]
Fixed, was a trailing slash upon domain update.
