### ISSUE TITLE
Mangahub not working

### ISSUE THREAD

**Issue by chailjc** [TheNetsky/Netskys-Extensions#88]
**Describe the bug**
Image below appears when loading Mangahub.

**To Reproduce**
1. Go to 'Discover' - 'Mangahub' or any Mangahub sources in library.
2. See error

**Expected behavior**
For mangahub to open as usual.

**Screenshots/Video**
![IMG_2224](https://github.com/TheNetsky/netskys-extensions/assets/89789474/72b721ec-ba96-41ae-b138-26afffd9b81d)

**App version**
- v0.8.7-r3, r9

**Source WITH source version**
- Mangahub 3.0.8

**Additional context**
Tried reinstalling app, logging in and out, reinstalling extension, repairing database but doesn't work.
Cloudflare still works as usual oddly enough.

**Comment by Techwiz34** [comment]
I also ran into this issue. I'm on iOS 16.7.2 and Mangahub source doesn't work for me either. I'm on app version v.0.8.6-r2 as well.

**Comment by TheNetsky** [comment]
Known, won't fix.
