### ISSUE TITLE
AsuraScans not working properly and not updating

### ISSUE THREAD

**Issue by Prosued** [TheNetsky/Netskys-Extensions#89]
**Describe the bug**
AsuraScans not updating

**To Reproduce**
Try to check AsuraScans or update related mangas and they won’t

**Expected behavior**
Check the new updated manga chapters that are on the site.

**Screenshots/Video**
N/A

**App version**
- v0.8.6-r2

**Source WITH source version**
- AsuraScans 3.0.6

**Comment by TheNetsky** [comment]
Wrong repo

**Comment by Prosued** [comment]
> Wrong repo

Then what’s the correct one?

**Comment by TheNetsky** [comment]
generic, also likely a issue on your part. Site has not changed.
