### ISSUE TITLE
AzoraWorld chapters won’t load

### ISSUE THREAD

**Issue by levwrld** [TheNetsky/Netskys-Extensions#90]
**Describe the bug**
the manga/manhwa won’t load any chapters, i tried picking different manhwas to see if the problem is only with one manhwa but every time i scroll to see the chapters they don’t load and i can’t even click on read.

**To Reproduce**
1. Go to 'discover'
2. Click on 'any manga'
3. Scroll down to 'chapters'

**Expected behavior**
the chapters of any manga should show up when scrolling down in the manga details or at least by clicking read.

**Screenshots/Video**
here is a screenshot and a video of the issue i’m facing.

![IMG_1932](https://github.com/TheNetsky/netskys-extensions/assets/149577191/2bc809b6-47c8-4f1c-b685-76c1ecb68d38)

https://github.com/TheNetsky/netskys-extensions/assets/149577191/045ff78d-2db3-418e-bf37-ba339170fa2a

**App version**
- v0.8.6-r2

**Source WITH source version**
- AzoraWorld 3.1.3

**Additional context**

**Comment by TheNetsky** [comment]
Wrong repo

**Comment by levwrld** [comment]
but it’s the one posted in the discord
