### ISSUE TITLE
asurascan issue

### ISSUE THREAD

**Issue by slyqq** [TheNetsky/Netskys-Extensions#93]
![IMG_4665](https://github.com/TheNetsky/netskys-extensions/assets/155333748/eac85c7e-3faf-4229-920d-1c3dc23ee981)
![IMG_4664](https://github.com/TheNetsky/netskys-extensions/assets/155333748/40085871-c201-4308-ac4c-91a9c61a7498)
**Describe the bug**
Ever since my phone updated the app to v0.86-r2 my asurascan extension is unable to operate. tried to uninstall and install the extension but it’s not working.
![IMG_4666](https://github.com/TheNetsky/netskys-extensions/assets/155333748/6b708d39-34e7-4ad4-9485-ebe52dbba393)

**Comment by kdmwest** [comment]
I have the same issue on asura, mangakalot and kunmanga
