### ISSUE TITLE
bato cannot load

### ISSUE THREAD

**Issue by shanashiina1407** [TheNetsky/Netskys-Extensions#94]
**Describe the bug**
Last week everything was fine but this week , i cannot read anything on bato source . Other sources are fine . I am using v0.8.7-r12 on ipad gen 9th. 
the error is : [INFO] [2024-01-09T17:11:34.982Z] [AppDelegate:requestNotificationPermission():174] Notification permission denied

All the manga are up to date but i cannot read any as the video below 

https://github.com/TheNetsky/netskys-extensions/assets/82970647/d4f4aa19-3acd-4150-a2a7-124a626df60c

the source is : 
![image](https://github.com/TheNetsky/netskys-extensions/assets/82970647/ac8569f8-7825-4f0c-b8bd-9b90d4236489)

**Comment by TheNetsky** [comment]
Wrong repo

**Comment by niclimcy** [comment]
And why are you using a dev repo lmao wth

**Comment by shanashiina1407** [comment]
> And why are you using a dev repo lmao wth

:( i didn't know . Somebody gave me a link on reddit or discord long time ago and told that i could add source from github and it worked
