### ISSUE TITLE
ZinManga

### ISSUE THREAD

**Issue by kdmwest** [TheNetsky/Netskys-Extensions#96]
**Describe the bug**
(Sorry this is my first self commenting) Homepage doesn't work and i am getting error messages

**Screenshots/Video**
![image](https://github.com/TheNetsky/netskys-extensions/assets/155338635/71d6ebc2-560c-4077-8175-9f22a7b77c3f)

**App version**
- v0.8.7-r12

**Source WITH source version**
- Readm 3.1.4

**Additional context**
Ios 17.3

**Comment by TheNetsky** [comment]
Did you do what the error says?

**Comment by kdmwest** [comment]
Yes when i click on the cloud icon it takes me to the website and it works just fine and when i go back to my homepage i still have nothing on there

**Comment by TheNetsky** [comment]
Seems to be working just fine for me. Cannot replicate.
