### ISSUE TITLE
ManhuaFast

### ISSUE THREAD

**Issue by ined14** [TheNetsky/Netskys-Extensions#97]
**Describe the bug**
The app said need to bypass with cloud icon but when i finished doing that it still the same, the app telling me to bypass it again, and sometimes it showing different error like "unable to parse slug"

**To Reproduce**
1. Go to 'manhuafast source/saved manhwa from that source'
2. Click on 'one of the manhwa from that source/saved from that source'

**Expected behavior**
Before should be done after bypassing it once, then i could read the manhwa from that source

**video**
https://github.com/TheNetsky/netskys-extensions/assets/55855817/afd51e9a-8893-4707-9b6c-f365463c869e

**App version**
- v0.8.8-r1

**Source WITH source version**
- manhuafast 3.1.3

**aditional info**
Ios 17.2.1

**Comment by TheNetsky** [comment]
I cannot replicate this, works fine for me after doing the bypass. Also open the issue on the correct repo.
