### ISSUE TITLE
ReadM - Search is not working

### ISSUE THREAD

**Issue by vregat** [TheNetsky/Netskys-Extensions#98]
**Describe the bug**
Search is not working for extension ReadM due to new domain.

**To Reproduce**
1. Go to Search
2. Write a title
3. Nothing shows up

**Expected behavior**
Should show results

**Screenshots/Video**

**App version**
- v0.8.7-r12

**Source WITH source version**
- Readm 2.1.6

**Additional context**
A change of domain from "https://readm.org" to "https://readm.today" should be enough to fix it. Atleast in Postman it worked with the new domain.

**Line**
- 33

_Can not create a pull request because do not have access to computer for a while._

**Comment by TheNetsky** [comment]
Fixed
