### ISSUE TITLE
JSError Error [PaperbackError(300)] JSError Error: AsyncOperationTimedOutError - undefined:undefined:undefined

### ISSUE THREAD

**Issue by AaltoTed** [TheNetsky/Netskys-Extensions#99]
**Describe the bug**
When searching (and adding a new source) from Mangadex, an error message will pop up. This happens only when there’s more than one word in the search bar. The genre filters work perfectly fine. The only thing I can think of that started this is me deleting the app and reinstalling it without logging out of the Mangadex extension.

**To Reproduce**
1. Delete app while logged into a Mangadex account
2. Reinstall paperback and extensions
3. Use search bar

**Expected behavior**
Mangadex search feature to be usable.

**Screenshots/Video**
Below is the exported paperback log. I used the ERROR message that popped up as the title.
[21-02.Paperback.txt](https://github.com/TheNetsky/netskys-extensions/files/14366349/21-02.Paperback.txt)

**App version**
- v0.8.7-r12

**Source WITH source version**
- Mangadex 3.0.4

**Additional context**

**Comment by TheNetsky** [comment]
Wrong repo
